#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

date=`date +%Y-%m-%d`
mkdir -p $install_dir
ynh_replace --match="__DOMAIN__" --replace="$domain" --file="../sources/publishconf.py"
ynh_replace --match="__PATH__" --replace="$path" --file="../sources/publishconf.py"
ynh_replace --match="__DOMAIN__" --replace="$domain" --file="../sources/pelicanconf.py"
ynh_replace --match="__PATH__" --replace="$path" --file="../sources/pelicanconf.py"
ynh_replace --match="__AUTHOR__" --replace="$author" --file="../sources/pelicanconf.py"
ynh_replace --match="__TITLE__" --replace="$title" --file="../sources/pelicanconf.py"
ynh_replace --match="__AUTHOR__" --replace="$author" --file="../sources/content/first-article.md"
ynh_replace --match="__DATE__" --replace="$date" --file="../sources/content/first-article.md"
cp -a ../sources/. $install_dir

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# SPECIFIC SETUP
#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building $app..."

pushd $install_dir
	python3 -m venv $install_dir/venv
	source $install_dir/venv/bin/activate
	pip install --upgrade pip
	ynh_hide_warnings pip install pelican markdown
	pelican -s pelicanconf.py -D
	deactivate
popd

# Somehow this directory is monitored, but not present upon install
mkdir -p "$install_dir/content/images"

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add $app --description="Static Site Generator" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
