#!/bin/bash

# Source app helpers
source _common.sh
source /usr/share/yunohost/helpers

app=$YNH_APP_INSTANCE_NAME
domain=$(ynh_app_setting_get $app domain)

# Delete app directory and configurations
sudo rm -rf "/var/www/"${app:-preventunsetvariable}
[[ -n $domain ]] && sudo rm -f "/etc/nginx/conf.d/${domain}.d/${app}.conf"

# Reload services
sudo service nginx reload || true
